In [1]:
import numpy as np

In [2]:
sample_list = [1,2,3]

In [3]:
list_array = np.array(sample_list)

In [4]:
list_array

array([1, 2, 3])

In [5]:
tup = (1,2,3)

In [6]:
my_tup_array = np.array(tup)

In [7]:
my_tup_array

array([1, 2, 3])

In [14]:
def multiply_loops(A, B):
    c=np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for k in range(B.shape[1]):
            c[i,k] = 0
            for j in range(B.shape[0]):
                n = A[i,j] * B[j,k]
                c[i,k] += n
    return c

In [15]:
def multiply_vector(A, B):
     return A @ B

In [16]:
X = np.random.random((100, 100))
Y = np.random.random((100, 100))

In [17]:
%timeit multiply_loops(X, Y)
%timeit multiply_vector(X, Y)

608 ms ± 7.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
20.6 µs ± 1.31 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [84]:
tup_dim = (3,4)
my_zeros_array = np.zeros(tup_dim, dtype = np.int16)

In [85]:
my_zeros_array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [23]:
tup_dim = (3,4)
my_ones_array = np.ones(tup_dim,dtype = np.int16)

In [24]:
my_ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [26]:
tup_dim = (3,4)
my_seven_array = np.full(tup_dim,7, dtype = np.int16)

In [27]:
my_seven_array

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]], dtype=int16)

In [32]:
my_identity_array = np.identity(4)

In [33]:
my_identity_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [110]:
my_rand_array = np.random.rand(3,4)

In [111]:
my_rand_array

array([[0.42957126, 0.1900357 , 0.67999376, 0.69999429],
       [0.87517495, 0.7474263 , 0.14038584, 0.93918208],
       [0.17410884, 0.07894948, 0.00098334, 0.8659132 ]])

In [112]:
tup_dim = (3,4)

In [124]:
my_uninitialized_array = np.empty(tup_dim)

In [125]:
my_uninitialized_array

array([[0.42957126, 0.1900357 , 0.67999376, 0.69999429],
       [0.87517495, 0.7474263 , 0.14038584, 0.93918208],
       [0.17410884, 0.07894948, 0.00098334, 0.8659132 ]])

In [135]:
my_range_array = np.arange(10,30,5)

In [136]:
my_range_array

array([10, 15, 20, 25])

In [143]:
my_spaced_array = np.linspace(0,30,6)

In [144]:
my_spaced_array

array([ 0.,  6., 12., 18., 24., 30.])

In [154]:
array_A = np.array([ [3,4,6], [0,8,1]])

In [159]:
array_A.ndim

2

In [160]:
array_A

array([[3, 4, 6],
       [0, 8, 1]])

In [161]:
array_A.shape

(2, 3)

In [162]:
array_A.size

6

In [164]:
array_A.dtype

dtype('int64')

In [165]:
array_A.itemsize

8

In [174]:
my_array = np.array([[1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16]])

In [183]:
my_array.ndim

2

In [184]:
my_array.shape

(3, 4)

In [185]:
my_array.dtype

dtype('int64')

In [186]:
my_array.size

12

In [187]:
import os

In [188]:
import pandas as pd
# defining housing.csv file path
HOUSING_PATH =  '/cxldata/datasets/project/housing'
# reading the large housing.csv file using pandas
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
# extracting only a few rows (5 rows) of data from the pandas dataframe 'my_df'
my_df = housing_raw.iloc[ : 5]
# creating a new small csv file - 'housing_short.csv' - containing the above extracted 5 rows of data
my_df.to_csv('housing_short.csv', index=False)

In [200]:
import numpy as np
import os

# using pandas to load a large csv file (housing.csv) and creating a new smaller csv file out of it after extracting only a few rows of data from it.
import pandas as pd
HOUSING_PATH =  '/cxldata/datasets/project/housing'
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
my_df = housing_raw.iloc[ : 5]
my_df.to_csv('housing_short.csv', index=False)

# loading the smaller csv file housing_short.csv using NumPy's loadtxt() function

FILE = 'housing_short.csv'

# defining load_housing_data() function, which takes filename (FILE) as input and loads this file using NumPy's loadtxt() function

def load_housing_data(file =FILE ):
    return np.loadtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'), 'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skiprows=1, unpack=True)

# calling the above defined load_housing_data() function, which returns various column values as NumPy arrays

longitude_arr, latitude_arr, housing_median_age_arr, total_rooms_arr, total_bedrooms_arr, population_arr, households_arr, median_income_arr, median_house_value_arr, ocean_proximity_arr = load_housing_data()

# printing the values of NumPy array - median_house_value_arr - that we got above.  
# median_house_value_arr contains values of median_house_value column of the csv file - housing_short.csv

print(median_house_value_arr)

[452600. 358500. 352100. 341300. 342200.]


In [210]:
HOUSING_PATH = '/cxldata/datasets/project/housing'

In [211]:
FILE = os.path.join(HOUSING_PATH, "housing.csv")

In [212]:
def load_housing_dataset(file=FILE):
    return np.genfromtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skip_header=1, filling_values = 99999999, unpack=False)

In [213]:
result_arr = load_housing_dataset()

In [214]:
print(len(result_arr))

20640


In [223]:
my_arr = np.array([ [0,1], [2,3] ])

my_arr.resize((3,4))

In [224]:
print(my_arr)

[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]


In [226]:
my_arr = np.array([[1,2,3,4], [5,6,7,8]])

my_arr.resize((3,4))

In [227]:
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 0, 0, 0]])

In [14]:
import numpy as np
my_arr = np.arange(9)

my_new_arr = my_arr.reshape(-1,3)

In [15]:
my_new_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
my_first_arr = np.array([1,2,3,4,5,6,7,8])

my_new_arr = my_first_arr.reshape((2,4))

In [17]:
print(my_new_arr)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
print(my_first_arr)

[1 2 3 4 5 6 7 8]


In [19]:
import numpy as np
my_second_arr = np.arange(9)
my_second_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
my_updated_arr = my_second_arr.reshape(-1,3)
print(my_updated_arr)
print(my_second_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [30]:
import numpy as np
from sklearn.datasets import load_sample_image

In [31]:
china = load_sample_image("china.jpg")

In [32]:
china.shape

(427, 640, 3)

In [33]:
print(china)

[[[174 201 231]
  [174 201 231]
  [174 201 231]
  ...
  [250 251 255]
  [250 251 255]
  [250 251 255]]

 [[172 199 229]
  [173 200 230]
  [173 200 230]
  ...
  [251 252 255]
  [251 252 255]
  [251 252 255]]

 [[174 201 231]
  [174 201 231]
  [174 201 231]
  ...
  [252 253 255]
  [252 253 255]
  [252 253 255]]

 ...

 [[ 88  80   7]
  [147 138  69]
  [122 116  38]
  ...
  [ 39  42  33]
  [  8  14   2]
  [  6  12   0]]

 [[122 112  41]
  [129 120  53]
  [118 112  36]
  ...
  [  9  12   3]
  [  9  15   3]
  [ 16  24   9]]

 [[116 103  35]
  [104  93  31]
  [108 102  28]
  ...
  [ 43  49  39]
  [ 13  21   6]
  [ 15  24   7]]]


In [34]:
image = china[150:220,130:250]

In [35]:
image.shape

(70, 120, 3)

In [36]:
height, width, channels = image.shape

In [40]:
image_grayscale = image.mean(axis=2).astype(np.float32)

In [42]:
image_grayscale.shape

(70, 120)

In [50]:
images = image_grayscale.reshape(1, height, width, 1)

In [51]:
images.shape

(1, 70, 120, 1)

In [117]:
import numpy as np

my_orig_arr = np.array((1, 15, 3, 9, 26, 7, 89, 12))

In [90]:
my_rev_arr = my_orig_array[::-1]

In [91]:
print(my_rev_arr)

[12 89  7 26  9  3 15  1]


In [92]:
my_orig_arr2 = np.array((2, 9, 17, 13, 1, 4, 20, 57))

In [93]:
my_orig_arr2[2:5] = -6

In [94]:
print(my_orig_arr2)

[ 2  9 -6 -6 -6  4 20 57]


In [95]:
arr = [1, 3, 5, 10, 4, 15]

In [96]:
arr[1 : 4]  = -3

TypeError: can only assign an iterable

In [97]:
apple = np.array((1, 8, 23, 3, 18, 91, 7, 15))

In [98]:
apple_slice = apple[1:4]

In [99]:
print(apple_slice)

[ 8 23  3]


In [100]:
print(apple)

[ 1  8 23  3 18 91  7 15]


In [101]:
apple_slice[1] = 99999

In [102]:
print(apple_slice)

[    8 99999     3]


In [103]:
print(apple)

[    1     8 99999     3    18    91     7    15]


In [104]:
apple_slice_new = apple[2:5].copy()

In [105]:
apple_slice_new[1] = 222222

In [106]:
print(apple_slice_new)

[ 99999 222222     18]


In [107]:
print(apple)

[    1     8 99999     3    18    91     7    15]


In [1]:
from sklearn.datasets import load_sample_image

In [2]:
import numpy as np

In [3]:
china = load_sample_image("china.jpg")

In [4]:
portion = china[120:250,110:230]

In [5]:
portion.shape

(130, 120, 3)

In [10]:
portion

array([[[ 62,  61,  56],
        [ 25,  22,  15],
        [ 28,  29,  21],
        ...,
        [ 21,  27,  23],
        [ 25,  25,  23],
        [ 18,  13,  10]],

       [[ 33,  34,  29],
        [ 24,  24,  16],
        [ 38,  39,  33],
        ...,
        [ 21,  25,  24],
        [ 26,  24,  25],
        [ 29,  23,  25]],

       [[  3,   3,   1],
        [ 15,  14,  10],
        [ 29,  30,  25],
        ...,
        [ 30,  31,  33],
        [ 18,  16,  19],
        [ 20,  15,  19]],

       ...,

       [[ 35,  32,  25],
        [ 32,  32,  24],
        [ 28,  22,  22],
        ...,
        [ 70,  81,  85],
        [ 76,  88,  86],
        [ 93,  86,  68]],

       [[ 52,  51,  33],
        [ 52,  46,  20],
        [ 50,  43,  25],
        ...,
        [ 72,  76,  88],
        [ 94,  99, 105],
        [122, 104,  84]],

       [[ 58,  60,  39],
        [ 63,  62,  34],
        [ 65,  67,  46],
        ...,
        [ 90, 104, 105],
        [103, 119, 119],
        [127, 126, 108]]

In [11]:
multi_arr = np.arange(12).reshape(3,4)

In [12]:
print(multi_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
rows_wanted = np.array( [True, False, True] )

In [14]:
multi_arr_portion = multi_arr[rows_wanted, : ]

In [15]:
print(multi_arr_portion)

[[ 0  1  2  3]
 [ 8  9 10 11]]


In [16]:
import numpy as np

In [17]:
my_multi_arr = np.arange(20).reshape(4,5)

In [18]:
my_multi_arr_portion = my_multi_arr[2:4,2:5]

In [19]:
print(my_multi_arr_portion)

[[12 13 14]
 [17 18 19]]


In [27]:
my_2d_arr = np.arange(20).reshape(4,5)

In [28]:
my_1d_arr = my_2d_arr.ravel()

In [29]:
my_1d_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
a_arr = np.array([60,70,80,90])
b_arr = np.arange(4)

In [38]:
c_arr = a_arr + b_arr

In [39]:
print(c_arr)

[60 71 82 93]


In [40]:
d_arr = np.array([60,70,80,90])
e_arr = np.arange(4)

In [41]:
f_arr = d_arr - e_arr

In [42]:
print(f_arr)

[60 69 78 87]


In [59]:
A_arr = np.array([ [ 5,9], [4, 7] ])
B_arr = np.array( [ [2, 8], [1, 6] ] )

In [60]:
M_arr = A_arr * B_arr

In [61]:
print(M_arr)

[[10 72]
 [ 4 42]]


In [62]:
C_arr = np.array([ [ 5,9], [4, 7] ])
D_arr = np.array( [ [2, 8], [1, 6] ] )

In [64]:
P_arr = np.dot(C_arr,D_arr)

In [65]:
print(P_arr)

[[19 94]
 [15 74]]


In [82]:
R_div = np.array([ [ 25,65], [40, 14] ])
S_div = np.array([ [2, 10], [4, 5] ] )

In [83]:
T_div = R_div/S_div

In [84]:
print(T_div)

[[12.5  6.5]
 [10.   2.8]]


In [85]:
R_int_div = np.array([ [ 25,65], [40, 70] ])
S_int_div = np.array([ [2, 10], [8, 3] ] )

In [86]:
T_int_div = R_int_div//S_int_div

In [87]:
print(T_int_div)

[[12  6]
 [ 5 23]]


In [88]:
R_mod = np.array([ [ 20,65], [40, 70] ])
S_mod = np.array([ [2, 10], [8, 3] ] )

In [89]:
T_mod = R_mod%S_mod

In [90]:
print(T_mod)

[[0 5]
 [0 1]]


In [109]:
R_exp = np.array([ [ 4, 2], [3, 4 ] ] )
S_exp = np.array( [ [2, 10], [4, 5] ] )

In [110]:
T_exp = R_exp**S_exp

In [111]:
print(T_exp)

[[  16 1024]
 [  81 1024]]


In [120]:
U = np.array([ [ 22, 45], [90, 4 ] ] )

In [121]:
U[U<45]

array([22,  4])

In [127]:
X_stat = np.array([ [ 1, 2, 3], [ 4, -5, 6] ])

In [128]:
print(f'Mean = {X_stat.mean()}')

Mean = 1.8333333333333333


In [129]:
print(f'Mean = {X_stat.var()}')

Mean = 11.805555555555557


In [130]:
print(f'Mean = {X_stat.std()}')

Mean = 3.435921354681384


In [132]:
print(f'Mean = {X_stat.min()}')

Mean = -5


In [133]:
print(f'Mean = {X_stat.max()}')

Mean = 6


In [134]:
print(f'Mean = {X_stat.sum()}')

Mean = 11


In [135]:
print(f'Mean = {X_stat.prod()}')

Mean = -720


In [147]:
Z = np.arange(18).reshape(2,3,3)

In [149]:
print(Z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [150]:
print(Z.sum(axis=2))

[[ 3 12 21]
 [30 39 48]]


In [156]:
N = np.arange(6).reshape(3,2)

In [157]:
print(N)

[[0 1]
 [2 3]
 [4 5]]


In [158]:
print("Transpose = ", N.T)

Transpose =  [[0 2 4]
 [1 3 5]]


In [181]:
X_broad = np.ones((3,3))

In [182]:
print(X_broad)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [183]:
Y_broad = np.arange(3)

In [184]:
print(Y_broad)

[0 1 2]


In [185]:
Z_broad = X_broad+Y_broad

In [186]:
print(Z_broad)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
